# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{mercury-rails}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jeremy Jackson"]
  s.date = %q{2011-06-21}
  s.description = %q{A fully featured and advanced HTML5 WYSIWYG editor written in CoffeeScript on top of Rails 3.1}
  s.email = %q{jejacks0n@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "LICENSE",
    "README.rdoc",
    "VERSION",
    "app/assets/images/mercury/button.png",
    "app/assets/images/mercury/clippy.png",
    "app/assets/images/mercury/default-snippet.png",
    "app/assets/images/mercury/loading-dark.gif",
    "app/assets/images/mercury/loading-light.gif",
    "app/assets/images/mercury/search-icon.png",
    "app/assets/images/mercury/toolbar/editable/buttons.png",
    "app/assets/images/mercury/toolbar/markupable/buttons.png",
    "app/assets/images/mercury/toolbar/primary/_expander.png",
    "app/assets/images/mercury/toolbar/primary/_pressed.png",
    "app/assets/images/mercury/toolbar/primary/historypanel.png",
    "app/assets/images/mercury/toolbar/primary/insertcharacter.png",
    "app/assets/images/mercury/toolbar/primary/insertlink.png",
    "app/assets/images/mercury/toolbar/primary/insertmedia.png",
    "app/assets/images/mercury/toolbar/primary/inserttable.png",
    "app/assets/images/mercury/toolbar/primary/inspectorpanel.png",
    "app/assets/images/mercury/toolbar/primary/notespanel.png",
    "app/assets/images/mercury/toolbar/primary/objectspanel.png",
    "app/assets/images/mercury/toolbar/primary/preview.png",
    "app/assets/images/mercury/toolbar/primary/redo.png",
    "app/assets/images/mercury/toolbar/primary/save.png",
    "app/assets/images/mercury/toolbar/primary/todospanel.png",
    "app/assets/images/mercury/toolbar/primary/undo.png",
    "app/assets/images/mercury/toolbar/snippetable/buttons.png",
    "app/assets/javascripts/mercury.js",
    "app/assets/javascripts/mercury/dialog.js.coffee",
    "app/assets/javascripts/mercury/dialogs/backcolor.js.coffee",
    "app/assets/javascripts/mercury/dialogs/forecolor.js.coffee",
    "app/assets/javascripts/mercury/dialogs/formatblock.js.coffee",
    "app/assets/javascripts/mercury/dialogs/objectspanel.js.coffee",
    "app/assets/javascripts/mercury/dialogs/style.js.coffee",
    "app/assets/javascripts/mercury/history_buffer.js.coffee",
    "app/assets/javascripts/mercury/mercury.js.coffee",
    "app/assets/javascripts/mercury/modal.js.coffee",
    "app/assets/javascripts/mercury/modals/htmleditor.js.coffee",
    "app/assets/javascripts/mercury/modals/insertcharacter.js.coffee",
    "app/assets/javascripts/mercury/modals/insertlink.js.coffee",
    "app/assets/javascripts/mercury/modals/insertmedia.js.coffee",
    "app/assets/javascripts/mercury/modals/insertsnippet.js.coffee",
    "app/assets/javascripts/mercury/modals/inserttable.js.coffee",
    "app/assets/javascripts/mercury/native_extensions.js.coffee",
    "app/assets/javascripts/mercury/page_editor.js.coffee",
    "app/assets/javascripts/mercury/palette.js.coffee",
    "app/assets/javascripts/mercury/panel.js.coffee",
    "app/assets/javascripts/mercury/region.js.coffee",
    "app/assets/javascripts/mercury/regions/editable.js.coffee",
    "app/assets/javascripts/mercury/regions/markupable.js.coffee",
    "app/assets/javascripts/mercury/regions/snippetable.js.coffee",
    "app/assets/javascripts/mercury/select.js.coffee",
    "app/assets/javascripts/mercury/snippet.js.coffee",
    "app/assets/javascripts/mercury/snippet_toolbar.js.coffee",
    "app/assets/javascripts/mercury/statusbar.js.coffee",
    "app/assets/javascripts/mercury/table_editor.js.coffee",
    "app/assets/javascripts/mercury/toolbar.button.js.coffee",
    "app/assets/javascripts/mercury/toolbar.button_group.js.coffee",
    "app/assets/javascripts/mercury/toolbar.expander.js.coffee",
    "app/assets/javascripts/mercury/toolbar.js.coffee",
    "app/assets/javascripts/mercury/tooltip.js.coffee",
    "app/assets/javascripts/mercury/uploader.js.coffee",
    "app/assets/javascripts/mercury_loader.js",
    "app/assets/stylesheets/mercury.css",
    "app/assets/stylesheets/mercury/dialog.scss",
    "app/assets/stylesheets/mercury/mercury.scss",
    "app/assets/stylesheets/mercury/modal.scss",
    "app/assets/stylesheets/mercury/statusbar.scss",
    "app/assets/stylesheets/mercury/toolbar.scss",
    "app/assets/stylesheets/mercury/tooltip.scss",
    "app/assets/stylesheets/mercury/uploader.scss",
    "app/controllers/images_controller.rb",
    "app/controllers/mercury_controller.rb",
    "app/models/image.rb",
    "app/views/layouts/mercury.html.haml",
    "app/views/mercury/modals/character.html.haml",
    "app/views/mercury/modals/htmleditor.html.haml",
    "app/views/mercury/modals/link.html.haml",
    "app/views/mercury/modals/media.html.haml",
    "app/views/mercury/modals/sanitizer.html.haml",
    "app/views/mercury/modals/table.html.haml",
    "app/views/mercury/palettes/backcolor.html.haml",
    "app/views/mercury/palettes/forecolor.html.haml",
    "app/views/mercury/panels/history.html.haml",
    "app/views/mercury/panels/notes.html.haml",
    "app/views/mercury/panels/snippets.html.haml",
    "app/views/mercury/selects/formatblock.html.haml",
    "app/views/mercury/selects/style.html.haml",
    "app/views/mercury/snippets/example.html.haml",
    "app/views/mercury/snippets/example_options.html.haml",
    "config/engine.rb",
    "config/routes.rb",
    "db/migrate/20110526035601_create_images.rb",
    "features/editing/basic.feature",
    "features/step_definitions/debug_steps.rb",
    "features/step_definitions/web_steps.rb",
    "features/support/env.rb",
    "features/support/paths.rb",
    "features/support/selectors.rb",
    "lib/mercury-rails.rb",
    "log/.gitkeep",
    "mercury-rails.gemspec",
    "spec/javascripts/mercury/dialog_spec.js.coffee",
    "spec/javascripts/mercury/dialogs/backcolor_spec.js.coffee",
    "spec/javascripts/mercury/dialogs/forecolor_spec.js.coffee",
    "spec/javascripts/mercury/dialogs/formatblock_spec.js.coffee",
    "spec/javascripts/mercury/dialogs/objectspanel_spec.js.coffee",
    "spec/javascripts/mercury/dialogs/style_spec.js.coffee",
    "spec/javascripts/mercury/history_buffer_spec.js.coffee",
    "spec/javascripts/mercury/mercury_spec.js.coffee",
    "spec/javascripts/mercury/modals/htmleditor_spec.js.coffee",
    "spec/javascripts/mercury/modals/insertcharacter_spec.js.coffee",
    "spec/javascripts/mercury/modals/insertlink_spec.js.coffee",
    "spec/javascripts/mercury/modals/insertmedia_spec.js.coffee",
    "spec/javascripts/mercury/modals/insertsnippet_spec.js.coffee",
    "spec/javascripts/mercury/modals/inserttable_spec.js.coffee",
    "spec/javascripts/mercury/native_extensions_spec.js.coffee",
    "spec/javascripts/mercury/page_editor_spec.js.coffee",
    "spec/javascripts/mercury/palette_spec.js.coffee",
    "spec/javascripts/mercury/panel_spec.js.coffee",
    "spec/javascripts/mercury/region_spec.js.coffee",
    "spec/javascripts/mercury/regions/_markupable_.js.coffee",
    "spec/javascripts/mercury/regions/editable_spec.js.coffee",
    "spec/javascripts/mercury/regions/snippetable_spec.js.coffee",
    "spec/javascripts/mercury/select_spec.js.coffee",
    "spec/javascripts/mercury/snippet_spec.js.coffee",
    "spec/javascripts/mercury/snippet_toolbar_spec.js.coffee",
    "spec/javascripts/mercury/statusbar_spec.js.coffee",
    "spec/javascripts/mercury/table_editor_spec.js.coffee",
    "spec/javascripts/mercury/toolbar.button_group_spec.js.coffee",
    "spec/javascripts/mercury/toolbar.button_spec.js.coffee",
    "spec/javascripts/mercury/toolbar.expander_spec.js.coffee",
    "spec/javascripts/mercury/toolbar_spec.js.coffee",
    "spec/javascripts/mercury/tooltip_spec.js.coffee",
    "spec/javascripts/mercury/uploader_spec.js.coffee",
    "spec/javascripts/responses/blank.html",
    "spec/javascripts/spec_helper.js",
    "spec/javascripts/templates/mercury/dialog.html",
    "spec/javascripts/templates/mercury/dialogs/backcolor.html",
    "spec/javascripts/templates/mercury/dialogs/forecolor.html",
    "spec/javascripts/templates/mercury/dialogs/formatblock.html",
    "spec/javascripts/templates/mercury/dialogs/objectspanel.html",
    "spec/javascripts/templates/mercury/dialogs/style.html",
    "spec/javascripts/templates/mercury/modals/htmleditor.html",
    "spec/javascripts/templates/mercury/modals/insertcharacter.html",
    "spec/javascripts/templates/mercury/modals/insertlink.html",
    "spec/javascripts/templates/mercury/modals/insertmedia.html",
    "spec/javascripts/templates/mercury/modals/insertsnippet.html",
    "spec/javascripts/templates/mercury/modals/inserttable.html",
    "spec/javascripts/templates/mercury/page_editor.html",
    "spec/javascripts/templates/mercury/palette.html",
    "spec/javascripts/templates/mercury/panel.html",
    "spec/javascripts/templates/mercury/region.html",
    "spec/javascripts/templates/mercury/regions/editable.html",
    "spec/javascripts/templates/mercury/regions/snippetable.html",
    "spec/javascripts/templates/mercury/select.html",
    "spec/javascripts/templates/mercury/snippet.html",
    "spec/javascripts/templates/mercury/snippet_toolbar.html",
    "spec/javascripts/templates/mercury/statusbar.html",
    "spec/javascripts/templates/mercury/table_editor.html",
    "spec/javascripts/templates/mercury/toolbar.button.html",
    "spec/javascripts/templates/mercury/toolbar.button_group.html",
    "spec/javascripts/templates/mercury/toolbar.expander.html",
    "spec/javascripts/templates/mercury/toolbar.html",
    "spec/javascripts/templates/mercury/tooltip.html",
    "spec/javascripts/templates/mercury/uploader.html",
    "vendor/assets/javascripts/jquery-1.6.js",
    "vendor/assets/javascripts/jquery-ui-1.8.13.custom.js",
    "vendor/assets/javascripts/jquery.additions.js",
    "vendor/assets/javascripts/liquidmetal.js",
    "vendor/assets/javascripts/showdown.js"
  ]
  s.homepage = %q{http://github.com/jejacks0n/mercury}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{A fully featured and advanced HTML5 WYSIWYG editor written in CoffeeScript on top of Rails 3.1}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, ["= 3.1.0.rc4"])
      s.add_runtime_dependency(%q<paperclip>, [">= 0"])
      s.add_runtime_dependency(%q<formtastic>, [">= 0"])
      s.add_runtime_dependency(%q<json>, [">= 0"])
      s.add_runtime_dependency(%q<sass-rails>, ["~> 3.1.0.rc"])
      s.add_runtime_dependency(%q<coffee-script>, [">= 0"])
      s.add_runtime_dependency(%q<haml>, [">= 0"])
      s.add_development_dependency(%q<uglifier>, [">= 0"])
      s.add_development_dependency(%q<jquery-rails>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<sqlite3>, [">= 0"])
      s.add_development_dependency(%q<thin>, [">= 0"])
      s.add_development_dependency(%q<ruby-debug19>, [">= 0"])
      s.add_development_dependency(%q<evergreen>, [">= 0"])
    else
      s.add_dependency(%q<rails>, ["= 3.1.0.rc4"])
      s.add_dependency(%q<paperclip>, [">= 0"])
      s.add_dependency(%q<formtastic>, [">= 0"])
      s.add_dependency(%q<json>, [">= 0"])
      s.add_dependency(%q<sass-rails>, ["~> 3.1.0.rc"])
      s.add_dependency(%q<coffee-script>, [">= 0"])
      s.add_dependency(%q<haml>, [">= 0"])
      s.add_dependency(%q<uglifier>, [">= 0"])
      s.add_dependency(%q<jquery-rails>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<sqlite3>, [">= 0"])
      s.add_dependency(%q<thin>, [">= 0"])
      s.add_dependency(%q<ruby-debug19>, [">= 0"])
      s.add_dependency(%q<evergreen>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, ["= 3.1.0.rc4"])
    s.add_dependency(%q<paperclip>, [">= 0"])
    s.add_dependency(%q<formtastic>, [">= 0"])
    s.add_dependency(%q<json>, [">= 0"])
    s.add_dependency(%q<sass-rails>, ["~> 3.1.0.rc"])
    s.add_dependency(%q<coffee-script>, [">= 0"])
    s.add_dependency(%q<haml>, [">= 0"])
    s.add_dependency(%q<uglifier>, [">= 0"])
    s.add_dependency(%q<jquery-rails>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<sqlite3>, [">= 0"])
    s.add_dependency(%q<thin>, [">= 0"])
    s.add_dependency(%q<ruby-debug19>, [">= 0"])
    s.add_dependency(%q<evergreen>, [">= 0"])
  end
end

