#!/usr/bin/env ruby
require 'rubygems'
require 'bundler/setup'
require 'em-websocket'
require 'em-hiredis'
require File.expand_path('../lib/mercury/websocket_server', __FILE__)

EM.run do
  Mercury::WebsocketServer.new.start
end